ec2_key_pair_name          = "ppresto-ptfe-dev-key"
eks_cluster_version        = "1.27"
consul_version             = "1.16.3-ent"
consul_helm_chart_version  = "1.2.3"
consul_helm_chart_template = "values-server-sd.yaml"
consul_partition           = "default"
prefix                     = "corelogic"