apiVersion: v1
kind: ServiceAccount
metadata:
  name: myservice
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: default
  labels:
    app: myservice
    service: myservice
spec:
  selector:
    app: myservice
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-deployment
  namespace: default
  labels:
    app: myservice
    version: v1
    service: fake-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice
  template:
    metadata:
      namespace: default
      labels:
        app: myservice
        service: fake-service
    spec:
      serviceAccountName: myservice
      containers:
        - name: myservice
          image: nicholasjackson/fake-service:v0.25.2
          ports:
            - containerPort: 9090
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9090'
            # - name: 'UPSTREAM_URIS'
            #   value: 'http://schema-registry.query.consul:8080'
            - name: 'NAME'
              value: 'myservice'
            - name: 'MESSAGE'
              value: 'API response'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'TIMING_50_PERCENTILE'
              value: '20ms'
            - name: 'TIMING_90_PERCENTILE'
              value: '30ms'
            - name: 'TIMING_99_PERCENTILE'
              value: '40ms'
            - name: 'TIMING_VARIANCE'
              value: '10'
            - name: 'HTTP_CLIENT_APPEND_REQUEST'
              value: 'true'
            - name: 'LOG_LEVEL'
              value: 'debug'